</br><div id="res-form-ajax"><?php View::content() ?></div>

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header"><?php eh($titulo) ?></h1>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->

<?php echo Form::open(NULL, 'post', 'class="form-horizontal" role="form"') ?>

    <?php echo Form::hidden('rol.id') ?>

    <div class="form-group">
      <label class="control-label col-sm-3" for="">Nombre de Rol *:</label>
      <div class="col-sm-3">          
        <?php echo Form::text('rol.rol', 'class="form-control"') ?>
      </div>
    </div>

    <div class="form-group">
      <label class="control-label col-sm-3" for="">Plantilla a Usar * :</label>
      <div class="col-sm-3">          
         <?php echo Form::text('rol.plantilla', 'class="form-control"') ?>
      </div>
    </div>

    <div class="form-group">
      <label class="control-label col-sm-3" for="">Activo (Visible) :</label>
      <div class="col-sm-2">          
        <?php echo Form::select('menu.activo', array('1' => 'Si', '0' => 'No'), 'class="form-control"') ?>
      </div>
    </div>

    </BR>
    <div class="form-group">        
      <div class="col-sm-offset-3 col-sm-10">
         <?php echo Form::submit('Guardar Datos', 'class="btn btn-primary"') ?>
        <?php echo Html::linkAction('', 'Cancelar', 'class="btn btn-default"') ?>
      </div>
    </div> 

<?php echo Form::close() ?>

        <script type="text/javascript">
            $(function(){
                var url = <?php echo PUBLIC_PATH ?> + "admin/roles/agregar_padre/";
                $("#select_padres select").live('change',function(){
                    var padre = $('option:selected',this).text();
                    if ( $("#roles_padres").html().indexOf(padre) < 0 &&
                        $('option:selected',this).val() != "<?php @eh($rol->id) ?>" ) {
                        $.post(url + $('option:selected',this).val(),{},function(data){
                            $("#roles_padres").append(data);
                        });
                    }
                });

                $("#roles_padres .rol_padre span").live('click',function(){
                    $(this).parent().remove();
                });
<?php if (isset($rol) and $rol->padres) : ?>
<?php foreach (explode(',', $rol->padres) as $e) : ?>
                $.post(url + <?php eh($e) ?>,{},function(data){
                    $("#roles_padres").append(data);
                });
<?php endforeach ?>
<?php endif ?>
});
</script>              
