<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Roles (Perfiles) del Sistema</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>
<?php View::content() ?>
<?php
echo Form::open('admin/roles/eliminar', 'post', 'class="form_lista"');
View::partial('backend/barra_superior_listas', FALSE, array('texto' => 'Crear Rol'));
$dt = new DataTable($roles);
$dt->addHeaders(Form::check('seleccionar_todos', 'todos', NULL, FALSE));
$dt->addHeaders('id', 'Rol', 'plantilla a usar', 'Estado', 'Editar', 'Eliminar');
$dt->check('roles_id');
$dt->addFields('id', 'rol', 'plantilla');
$dt->imgLink('figuras/circulo_rojo.png|figuras/circulo_verde.png',
        'admin/roles/activar|admin/roles/desactivar', '', 'activo');
$dt->imgLink('figuras/editar.png', 'admin/roles/editar');
$dt->imgLinkConfirm('figuras/eliminar.png', 'admin/roles/eliminar', '', '¿Realmente desea Eliminar Este Rol?');
echo $dt->render('class="table table-bordered table-striped"');
echo Form::close();
?>

<script type="text/javascript">
$(document).ready(function() {
    $('#dataTables-backend').DataTable( {
        "language": {
            "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Spanish.json"
        },
        "columnDefs": [ { "searchable": false, "targets": 0, "orderable": false }, 
                        { "searchable": false, "targets": 4, "orderable": false },
                        { "searchable": false, "targets": 5, "orderable": false },
                        { "searchable": false, "targets": 6, "orderable": false } ],
        //"order": [[ 3, "asc" ]], 
        //"searching": false,
        "lengthMenu": [[10, 25, 50, -1], [10, 25, 50, "All"]]
    } );
} );
</script>