<?php echo Form::open('admin/privilegios/asignar_privilegios/') ?>

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">
            Privilegios de los Usuarios
            <span style="line-height: 16px;float: right;margin-right: 50px;">
                <?php echo Form::submit('Guardar Cambios', 'class="btn btn-primary"') ?>
            </span>
        </h1>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->

<div id="mensajes_flash" > <?php View::content() ?> </div>

<div class="row">
    <div class="col-lg-12">
        <div class="panel-body">
            <div class="dataTable_wrapper">

        <?php $ids_privilegios = array(); //variable para saber los privilegios de la pagina actual ?>
<?php if ($results) : ?>
                <table id="tabla_privilegios" class="table table-striped table-bordered table-hover">
                    <thead>
                        <tr>
                            <th rowspan="2"style="width: 200px">Recursos</th>
                            <th rowspan="2" style="width: 300px">Descripcion</th>
                            <th colspan="<?php echo count($roles) ?>" style="text-align: center; border-bottom:1px solid #DDD;">Roles</th>
                        </tr>
                        <tr>
            <?php foreach ($roles as $e) : ?>
                    <th style="text-align: center;border-left:1px solid #DDD;">
                        <a href="#" id="check_rol_<?php eh($e->id) ?>" class="check_roles">
                    <?php eh($e->rol) ?>
                </a>
            </th>
            <?php endforeach ?>
                </tr>
            </thead>
            <tbody>
        <?php foreach ($results as $item) : ?>
                        <tr>
                            <td><?php eh($item->recurso) ?></td>
                            <td><?php eh($item->descripcion) ?></td>
            <?php foreach ($roles as $e) : ?>
            <?php if (array_key_exists("{$e->id}-{$item->id}", $privilegios)) : ?>
            <?php $ids_privilegios[] = $privilegios["{$e->id}-{$item->id}"] ?>
                                <td class="check_rol_<?php eh($e->id) ?>">
                <?php echo Form::check("priv.{$e->id}_{$item->id}", "{$e->id}/{$item->id}", NULL, true) ?>
                            </td>
            <?php else: ?>
                                    <td class="check_rol_<?php eh($e->id) ?>">
                <?php echo Form::check("priv.{$e->id}_{$item->id}", "{$e->id}/{$item->id}") ?>
                                </td>
            <?php endif; ?>
            <?php endforeach ?>
                                </tr>
        <?php endforeach ?>
                                </tbody>
                            </table>

<?php else : // Si no hay items?>
                                        <h2>No hay ningún registro</h2>
<?php endif ?>
<?php echo Form::hidden('privilegios_pagina', NULL, join(',', $ids_privilegios)); ?>
<?php echo Form::close() ?>
                                        
            </div>
        </div>
    </div>
</div>
                                        
<script type="text/javascript">
$(document).ready(function() {
    $('#tabla_privilegios').DataTable( {
        "language": {
            "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Spanish.json"
        },
        "searching": false,
        "paging": false,
        "columnDefs": [ { "searchable": false, "targets": 2, "orderable": false },
                        { "searchable": false, "targets": 3, "orderable": false }, 
                        { "searchable": false, "targets": 4, "orderable": false }, 
                        { "searchable": false, "targets": 5, "orderable": false } ],
        //"order": [[ 3, "asc" ]], 
        //"searching": false,
        "lengthMenu": [[-1], ["All"]]
    } );
} );
</script>