<!DOCTYPE html>
<html lang="es">
    <head>
        <meta http-equiv="Content-Type" content="text/html" charset=UTF-8">
        <meta charset='<?php echo APP_CHARSET ?>' />
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">

        <title><?php echo Config::get('config.application.name') ?></title>
        
    </head>
    <body class="login">
        <div>
            <a class="hiddenanchor" id="signup"></a>
            <a class="hiddenanchor" id="signin"></a>
            <a class="hiddenanchor" id="restore"></a>

            <div class="login_wrapper"> 
                
               <div class="animate form login_form">
                    <section class="login_content">
                        <?php View::content() ?>
                        Forbidden, you don't have access to this site.
                    </section>
                </div>                  
            </div>
        </div>
    </body>
</html>
