</br><?php View::content() ?>

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">
            Recursos por Agregar al Sistema
            <?php echo Html::linkAction('', 'Volver', 'class="btn btn-default pull-right"') ?>
            <?php echo Html::linkAction('crear', 'Crear Recurso', 'class="btn btn-info pull-right" style="margin-right:10px;"') ?>
        </h1>
    </div>
    <!-- /.col-lg-12 -->
</div>

<?php echo Form::open() ?>
<?php //echo Ajax::form('res-form-ajax') ?>
        <p>
    <?php echo Form::submit('Guardar Recursos Seleccionados', 'name="guardar" class="btn btn-primary btn-large"') ?>
    </p>
    
    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th class="span4">Datos del Recurso</th>
                <th>Descripci&oacute;n</th>
                <th>Activo</th>
                <th>Agregar</th>
            </tr>
        </thead>
        <tbody>

        <?php foreach ($recursos as $index => $e) :++$index ?>
            <tr>
                <td>
                    <ul class="unstyled">
                        <li>
                            <strong>Recurso :</strong> <?php echo $e['recurso'] ?>
                        </li>
                        <li>
                            <strong> Modulo :</strong> <?php echo $e['modulo'] ?>
                        </li>
                        <li>
                            <strong>Controlador :</strong> <?php echo $e['controlador'] ?>
                        </li>
                        <li>
                            <strong>Accion :</strong> <?php echo $e['accion'] ?>
                        </li>
                    </ul>
                </td>
                <td>
                <?php echo Form::textarea("descripcion.$index", 'class="span6"') ?>
            </td>
            <td class="span1">
                <?php echo Form::radio("activo.$index", '1', NULL, TRUE) ?> Si <br/>
                <?php echo Form::radio("activo.$index", '0') ?> No
            </td>
            <td class="span1">
                <?php echo Form::check("check.$index", $index) ?>
            </td>
        </tr>
        <?php endforeach ?>
            </tbody>
        </table>

<?php echo Form::close() ?>
<style type="text/css" >
    table ul strong{
        display: inline-block;
        width: 90px;
    }

    table textarea{
        height: 60px;
    }

    table ul{
        margin-bottom: 0px;
    }

    .page-header h1 a{
        margin-left: 10px;
    }
</style>