<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Menus del Sistema</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>
<?php View::content() ?>
<?php
echo Form::open('admin/menu/eliminar', 'post', 'class="form_lista"');
View::partial('backend/barra_superior_listas',FALSE,array('texto' => 'Crear Menú'));
$dt = new DataTable($menus);
$dt->addHeaders(Form::check('seleccionar_todos', 'todos', NULL, FALSE));
$dt->addHeaders('Texto a Mostrar', 'Menu Padre');
$dt->addHeaders('Recurso al que Accede', 'Posición');
$dt->addHeaders('Estado', 'Editar', 'Eliminar');
$dt->check('menu_id');
$dt->addFields('nombre', 'padre', 'recurso', 'posicion');
$dt->imgLink('figuras/circulo_rojo.png|figuras/circulo_verde.png',
        'admin/menu/activar|admin/menu/desactivar', '', 'activo');
$dt->imgLink('figuras/editar.png', 'admin/menu/editar');
$dt->imgLinkConfirm('figuras/eliminar.png', 'admin/menu/eliminar', '',
        '¿Realmente desea Eliminar El Menu ?');
echo $dt->render('class="table table-bordered table-striped"');
echo Form::close();
?>

<script type="text/javascript">
$(document).ready(function() {
    $('#dataTables-backend').DataTable( {
        "language": {
            "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Spanish.json"
        },
        "columnDefs": [ { "searchable": false, "targets": 0, "orderable": false }, 
                        { "searchable": false, "targets": 4, "orderable": false }, 
                        { "searchable": false, "targets": 5, "orderable": false },
                        { "searchable": false, "targets": 6, "orderable": false },
                        { "searchable": false, "targets": 7, "orderable": false } ],
        //"order": [[ 3, "asc" ]], 
        //"searching": false,
        "lengthMenu": [[10, 25, 50, -1], [10, 25, 50, "All"]]
    } );
} );
</script>