<div id='cabecera' class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <?php echo Html::link('', Html::img('Logo_G+_panel_sites.png', 'G+ Desarrollo Web', 'width= "40px"'), 'class="brand"') ?>
            <div class="nav-collapse pull-right">
                <ul class="nav">
                    <li><?php echo Html::link('usuarios', 'Administración') ?></li>
                </ul>
            </div>
        </div>
    </div>
</div>