<?php 
    $us =  Load::model('usuarios')->find_first(Auth::get('id'));
    if($us->img){ $img = "upload/usuarios/$us->img"; } else { $img = 'user.png'; }
    $nombre = $us->nombres . ' ' . $us->apellido;;
?>

<div class="col-md-3 left_col">
    <div class="left_col scroll-view">
        <div class="navbar nav_title" style="border: 0;">
            <a href="" class="site_title"><i class="fa fa-paw"></i> <span><?php echo Config::get('config.application.name') ?></span></a>
        </div>
        <div class="clearfix"></div>

        <!-- menu profile quick info -->
        <div class="profile">
            <div class="profile_pic">
                <?php echo Html::img($img, null, 'class="img-circle profile_img"')?>
            </div>
            <div class="profile_info">
                <span>Hola,</span>
                <h2><?php echo $nombre ?></h2>
            </div>
        </div>
        <!-- /menu profile quick info -->
        <div class="clearfix"></div>
        <!-- sidebar menu -->
        <?php View::renderSidebar(Sidebar::BACKEND) ?>
        <!-- /sidebar menu -->


        <!-- /menu footer buttons -->
        <div class="sidebar-footer hidden-small">
            <!--
            <?php echo Html::link('admin/usuarios/logout', 
                    '<span class="glyphicon glyphicon-cog" aria-hidden="true"></span>', 
                    'data-toggle="tooltip" data-placement="top" title="Settings"')?>
            
            <a data-toggle="tooltip" data-placement="top" title="Settings">
                <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
            </a>
            
            <a data-toggle="tooltip" data-placement="top" title="FullScreen">
                <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
            </a>
            <a data-toggle="tooltip" data-placement="top" title="Lock">
                <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
            </a>
            
            <?php echo Html::link('admin/usuarios/logout', 
                    '<span class="glyphicon glyphicon-off" aria-hidden="true"></span>', 
                    'data-toggle="tooltip" data-placement="top" title="Logout"')?>
            <!--
            <a data-toggle="tooltip" data-placement="top" title="Logout">
                <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
            </a>
            -->
        </div>
        <!-- /menu footer buttons -->
    </div>
</div>
<li><?php //echo Html::link('admin/usuarios/logout', '<i class="fa fa-sign-out pull-right"></i> Salir')?></li>
