<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Nuevo Usuario</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->

<div id="res-form-ajax"><?php View::content() ?></div>

<?php echo Form::open(NULL, 'post', 'class="form-horizontal" role="form"') ?>

    <?php echo Form::hidden('usuario.id') ?>

    <div class="form-group">
      <label class="control-label col-sm-3" for="">Nombre de Usuario (Login)* :</label>
      <div class="col-sm-4">          
        <?php echo Form::text('usuario.login', 'class="form-control" required="required"') ?>
      </div>
    </div>

    <div class="form-group">
      <label class="control-label col-sm-3" for="">Contrase&ntilde;a* :</label>
      <div class="col-sm-3">          
        <?php echo Form::pass('usuario.clave', 'class="form-control" required="required"') ?>
      </div>
    </div>

    <div class="form-group">
      <label class="control-label col-sm-3" for="">Reintroducir Contrase&ntilde;a* :</label>
      <div class="col-sm-3">          
        <?php echo Form::pass('usuario.clave2', 'class="form-control" required="required"') ?>
      </div>
    </div>

    <div class="form-group">
      <label class="control-label col-sm-3" for="">Nombres *:</label>
      <div class="col-sm-3">          
        <?php echo Form::text('usuario.nombres', 'class="form-control" required="required"') ?>
      </div>
    </div>

    <div class="form-group">
      <label class="control-label col-sm-3" for="">Apellido *:</label>
      <div class="col-sm-3">          
        <?php echo Form::text('usuario.apellido', 'class="form-control" required="required"') ?>
      </div>
    </div>

    <div class="form-group">
      <label class="control-label col-sm-3" for="">Teléfono :</label>
      <div class="col-sm-3">          
        <?php echo Form::text('usuario.telefono', 'class="form-control"') ?>
      </div>
    </div>

    <div class="form-group">
      <label class="control-label col-sm-3" for="">Celular :</label>
      <div class="col-sm-3">          
        <?php echo Form::text('usuario.celular', 'class="form-control"') ?>
      </div>
    </div>

    <div class="form-group">
      <label class="control-label col-sm-3" for="">Email *:</label>
      <div class="col-sm-4">          
        <?php echo Form::text('usuario.email', 'class="form-control" required="required"') ?>
      </div>
    </div>

    <div class="form-group">
      <label class="control-label col-sm-3" for="">Domicilio :</label>
      <div class="col-sm-6">          
        <?php echo Form::text('usuario.domicilio', 'class="form-control"') ?>
      </div>
    </div>

    <div class="form-group">
      <label class="control-label col-sm-3" for="">Rol del Usuario* : </label>
      <div class="col-sm-4">          
        <?php 
        if($dev){    
            echo Form::dbSelect('roles_id', 'rol', array('roles','find', 'activo = 1 order by rol'), 'Seleccione', 'class="form-control" required="required"');
        } else {
            echo Form::dbSelect('roles_id', 'rol', array('roles','findRolesAdmin', 'activo = 1 order by rol'), 'Seleccione', 'class="form-control" required="required"');  
        }
          ?>
      </div>
    </div>

    </BR>
    <div class="form-group">        
      <div class="col-sm-offset-3 col-sm-10">
         <?php echo Form::submit('Guardar Datos', 'class="btn btn-primary"') ?>
        <?php echo Html::linkAction('index', 'Cancelar', 'class="btn btn-default"') ?>
      </div>
    </div> 

<?php echo Form::close() ?>

