<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Edición Datos Usuario <small><?php eh(strtoupper($usuario->login)) ?></small></h1>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->

<div id="res-form-ajax"><?php View::content() ?></div>

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Panel
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <!-- Nav tabs -->
                <ul class="nav nav-tabs">
                    <li class="active"><a href="#datos-personales" data-toggle="tab">Datos Personales</a></li>
                    <li><a href="#clave" data-toggle="tab">Contrase&ntilde;a</a></li>
                    <li><a href="#foto" role="tab" data-toggle="tab">Foto de Perfil</a></li>                    
                </ul>

                <!-- Tab panes -->
                <div class="tab-content">
                    
                    <!--TAB DATOS PERSONALES -->
                    <div class="tab-pane fade in active" id="datos-personales">
                        </br>
                        <?php echo Form::open(NULL, 'post', 'class="form-horizontal" role="form"') ?>
                        <?php echo Form::hidden('usuario.id') ?>

                        <div class="form-group">
                            <label class="control-label col-sm-3" for="">Login *:</label>
                            <div class="col-sm-4">          
                                <?php echo Form::text('usuario.login', 'class="form-control" required="required"') ?>
                            </div>
                        </div>                      

                        <div class="form-group">
                            <label class="control-label col-sm-3" for="">Nombres *:</label>
                            <div class="col-sm-3">          
                                <?php echo Form::text('usuario.nombres', 'class="form-control" required="required"') ?>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-sm-3" for="">Apellido *:</label>
                            <div class="col-sm-3">          
                                <?php echo Form::text('usuario.apellido', 'class="form-control" required="required"') ?>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-sm-3" for="">Teléfono :</label>
                            <div class="col-sm-3">          
                                <?php echo Form::text('usuario.telefono', 'class="form-control"') ?>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-sm-3" for="">Celular :</label>
                            <div class="col-sm-3">          
                                <?php echo Form::text('usuario.celular', 'class="form-control"') ?>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-sm-3" for="">Email *:</label>
                            <div class="col-sm-4">          
                                <?php echo Form::text('usuario.email', 'class="form-control" required="required"') ?>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-sm-3" for="">Domicilio :</label>
                            <div class="col-sm-6">          
                                <?php echo Form::text('usuario.domicilio', 'class="form-control"') ?>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-sm-3" for="">Rol del Usuario* : </label>
                            <div class="col-sm-4">          
                            <?php 
                            if($dev){    
                                echo Form::dbSelect('roles_id', 'rol', array('roles','find', 'activo = 1 order by rol'), 'Seleccione', 'class="form-control" required="required"');
                            } else {
                                echo Form::dbSelect('roles_id', 'rol', array('roles','findRolesAdmin', 'activo = 1 order by rol'), 'Seleccione', 'class="form-control" required="required"');  
                            }
                            ?>
                            </div>
                        </div>

                        </BR>
                        <div class="form-group">        
                            <div class="col-sm-offset-3 col-sm-10">
                                <?php echo Form::submit('Guardar Datos', 'class="btn btn-primary"') ?>
                                <?php echo Html::linkAction('', 'Cancelar', 'class="btn btn-default"') ?>
                            </div>
                        </div> 

                        <?php echo Form::close() ?>

                    </div>

                    <!--TAB CONTRASEÑA -->
                    <div class="tab-pane fade" id="clave">
                        </br>
                        <?php echo Form::open(NULL, 'post', 'class="form-horizontal" role="form"') ?>
                        <?php //echo Ajax::form('res-datos-personales', NULL, 'form-horizontal', '', ' role="form"') //Form::open() ?>

                        <div class="form-group">
                            <label class="control-label col-sm-3" for="">Contrase&ntilde;a* :</label>
                            <div class="col-sm-3">          
                                <?php echo Form::pass('usuario2.nueva_clave', 'class="form-control"') ?>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-sm-3" for="">Reintroducir Contrase&ntilde;a* :</label>
                            <div class="col-sm-3">          
                                <?php echo Form::pass('usuario2.nueva_clave2', 'class="form-control"') ?>
                            </div>
                        </div>

                        </BR>
                        <div class="form-group">        
                            <div class="col-sm-offset-3 col-sm-10">
                                <?php echo Form::submit('Guardar Datos', 'class="btn btn-primary"') ?>
                                <?php echo Html::linkAction('', 'Cancelar', 'class="btn btn-default"') ?>
                            </div>
                        </div> 

                        <?php echo Form::close() ?>
                    </div>  
                    
                    <!--TAB FOTO PERFIL -->
                <div class="tab-pane fade" id="foto">
                    </br>
                    
                    <?php echo Form::openMultipart(NULL, 'class="form-horizontal" role="form"') ?>
                    <?php echo Form::hidden('usuario3.id', null, $usuario->id) ?>
                    <div class="form-group">
                        <label class="control-label col-sm-3" for="">Foto :</label>
                        <div class="col-sm-3">  
                            <?php if($usuario->img){
                                echo Html::img('upload/usuarios/' . $usuario->img, '', 'class="img-responsive avatar-view"');
                            } else { 
                                echo Html::img('user.png', '', 'class="img-responsive avatar-view"');
                            }
                            ?>
                        </div>
                    </div>
                    
                    <div class="form-group">
                        <label class="control-label col-sm-3" for="">Archivo :</label>
                        <div class="col-sm-3">          
                            <?php echo Form::file('img', 'class="form-control"') ?>
                        </div>
                    </div>
                    </BR>                   

                    <div class="form-group">        
                        <div class="col-sm-offset-3 col-sm-10">
                            <?php echo Form::submit('Guardar Datos', 'class="btn btn-primary"') ?>
                            <?php echo Html::linkAction('', 'Cancelar', 'class="btn btn-default"') ?>
                        </div>
                    </div> 

                    <?php echo Form::close() ?>
                </div>    
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
        <!-- /.col-lg-6 -->

    </div>
    <!-- /.row -->
