<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Usuarios del Sistema</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->

<?php View::content() ?>

<?php
    View::partial('backend/barra_superior_listas', FALSE, array('texto' => 'Crear Usuario', 'opciones' => FALSE));
    $dt = new DataTable($usuarios);
    $dt->addHeaders('id', 'Login', 'Nombres', 'Correo Electronico', 'Estado', 'Editar', 'Eliminar');
    $dt->addFields('id', 'login', 'nombres', 'email');
    $dt->cssLink('class="fa fa-user" style="color:red; font-size:20px; padding-left:20px;" | class="fa fa-user" style="color:green; font-size:20px; padding-left:20px;"', 'admin/usuarios/activar|admin/usuarios/desactivar', '', 'activo');
    $dt->cssLink('class="fa fa-edit" style="color:green; font-size:20px; padding-left:20px;"', 'admin/usuarios/editar');
    $dt->cssLinkConfirm('fa fa-close', 'style="color:red; font-size:20px; padding-left:20px;"', 'admin/usuarios/eliminar', '', 'Confirmar si desea Eliminar Este Usuario?');
    echo $dt->render('class="table table-bordered table-striped"');
?>


<script type="text/javascript">
    $(document).ready(function () {
        $('#dataTables-backend').DataTable({
            "language": {
                "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Spanish.json"
            },
            "columnDefs": [{"searchable": false, "targets": 4, "orderable": false},
                {"searchable": false, "targets": 5, "orderable": false},
                {"searchable": false, "targets": 6, "orderable": false}],
            //"order": [[ 3, "asc" ]], 
            //"searching": false,
            "lengthMenu": [[10, 25, 50, -1], [10, 25, 50, "All"]]
        });
    });
</script>

