<div class="row">
    <div class="col-lg-12">
        <?php if($logo) { 
            echo Html::img('upload/apps/' . $logo, null, 'class="nav navbar-right"');
        } ?>
        <h1 class="page-header"><?php echo h($title) ?></h1>        
    </div>    
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->
<?php 
    $action = Router::get('action'); 
    $attr = null;
    if($action == 'view') $attr = 'DISABLED';
?>
<div id="res-form-ajax"><?php View::content() ?></div>

<?php echo Form::openMultipart(null, 'class="form-horizontal" role="form"') ?>

<?php echo Form::hidden('app.id') ?>

<div class="form-group">
    <label class="control-label col-sm-3" for="">Nombre de la App *:</label>
    <div class="col-sm-3">          
        <?php echo Form::text('app.name', 'class="form-control"' . $attr) ?>
    </div>
</div>

<div class="form-group">
    <label class="control-label col-sm-3" for="">Version :</label>
    <div class="col-sm-2">          
        <?php echo Form::text('app.version', 'class="form-control"' . $attr) ?>
    </div>
</div>

<div class="form-group">
    <label class="control-label col-sm-3" for="">Version Name :</label>
    <div class="col-sm-2">          
        <?php echo Form::text('app.version_name', 'class="form-control"' . $attr) ?>
    </div>
</div>

<div class="form-group">
    <label class="control-label col-sm-3" for="">Google Play (link) :</label>
    <div class="col-sm-7">          
        <?php echo Form::text('app.googleplay_link', 'class="form-control"' . $attr) ?>
    </div>
</div>

<div class="form-group">
    <label class="control-label col-sm-3" for="">Folder (Backend) *:</label>
    <div class="col-sm-3">          
        <?php echo Form::text('app.folder', 'class="form-control"' . $attr) ?>
    </div>
</div>

<div class="form-group">
    <label class="control-label col-sm-3" for="">Logo :</label>
    <div class="col-sm-4">          
        <?php echo Form::file('logo', $attr) ?>
    </div>
</div>

<div class="form-group">
    <label class="control-label col-sm-3" for="">Status *:</label>
    <div class="col-sm-3">          
        <?php echo Form::select('app.status', array('In Progress' => 'In Progress', 'Published' => 'Published') , 'class="form-control"' . $attr) ?>
    </div>
</div>

<div class="form-group">
    <label class="control-label col-sm-3" for="">Created :</label>
    <div class="col-sm-2">          
        <?php echo Form::text('app.created_at', 'class="form-control" DISABLED') ?>
    </div>
</div>
<div class="form-group">
    <label class="control-label col-sm-3" for="">Modified :</label>
    <div class="col-sm-2">          
        <?php echo Form::text('app.modified_in', 'class="form-control" DISABLED') ?>
    </div>
</div>

<div class="form-group">
    <label class="control-label col-sm-3" for="">Active *:</label>
    <div class="col-sm-2">          
        <?php echo Form::select('app.active', array(1 => 'Yes', 0 => 'No') , 'class="form-control"' . $attr) ?>
    </div>
</div>

</BR>
<div class="form-group">        
    <div class="col-sm-offset-3 col-sm-10">
        <?php if($attr == null){ ?>
            <?php echo Form::submit('Save', 'class="btn btn-success"') ?>
            <?php echo Html::linkAction('', 'Cancel', 'class="btn btn-primary"') ?>
        <?php } else { ?>
            <?php echo Html::linkAction('', 'Back', 'class="btn btn-default"') ?>
        <?php } ?>
    </div>
</div> 

<?php echo Form::close() ?>